using System.Collections.Generic;
using UnityEngine;

public static class Localizer
{
	private static readonly Dictionary<string, string> english = new Dictionary<string, string>
	{
		{ "phone_toriel_0_0_0", "tori_neutral`snd_txttor`* 您好。\n^10* 这里是TORIEL。" },
		{ "phone_toriel_0_0_1", "tori_worry`snd_txttor`* Kris...?^10\n* Is something wrong?" },
		{ "phone_toriel_0_0_2", "tori_worry`snd_txttor`* You sound upset." },
		{ "phone_toriel_0_0_3", "tori_worry`snd_txttor`* Why don't you hurry\n  over to my home?" },
		{ "phone_toriel_0_0_4", "tori_worry`snd_txttor`* You can tell me\n  everything on your\n  mind when you come." },
		{ "phone_toriel_0_0_5", "* (滴...)" },
		{ "phone_toriel_7_0_0", "tori_neutral`snd_txttor`* 您好。\n^10* 这里是TORIEL。" },
		{ "phone_toriel_7_0_1", "tori_worry`snd_txttor`* 一张花床？" },
		{ "phone_toriel_7_0_2", "tori_happy`snd_txttor`* 我很高兴它们能接住你们。" },
		{ "phone_toriel_7_0_3", "tori_neutral`snd_txttor`* 我会时不时地来照顾它们。" },
		{ "phone_toriel_7_0_4", "tori_worry`snd_txttor`* 我很好奇这些花接住你们俩\n  后还好不好。" },
		{ "phone_toriel_7_0_5", "* (滴...)" },
		{ "phone_toriel_8_0_0", "tori_neutral`snd_txttor`* 您好。\n^10* 这里是TORIEL。" },
		{ "phone_toriel_8_0_1", "tori_worry`snd_txttor`* 一朵花骚扰了你们俩？" },
		{ "phone_toriel_8_0_2", "tori_worry`snd_txttor`* 我对此深感抱歉。" },
		{ "phone_toriel_8_0_3", "tori_neutral`snd_txttor`* 我偶尔会在附近看到那朵花。" },
		{ "phone_toriel_8_0_4", "tori_worry`snd_txttor`* 我不知道为什么一朵花能\n  如此残暴。" },
		{ "phone_toriel_8_0_5", "* (滴...)" },
		{ "phone_toriel_9_0_0", "tori_neutral`snd_txttor`* 您好。\n^10* 这里是TORIEL。" },
		{ "phone_toriel_9_0_1", "tori_neutral`snd_txttor`* 遗迹的入口十分安静，\n^10  对吧？" },
		{ "phone_toriel_9_0_2", "tori_neutral`snd_txttor`* 我想让这个地方看起来\n  很吸引人。" },
		{ "phone_toriel_9_0_3", "tori_annoyed`snd_txttor`* Of course,^10 this is in\n  spite of the reputation\n  that humans have here." },
		{ "phone_toriel_9_0_4", "tori_worry`snd_txttor`* 这个我们待会再聊。" },
		{ "phone_toriel_9_0_5", "* (滴...)" },
		{ "phone_toriel_9_1_0", "tori_worry`snd_txttor`* 等你们到了我家再说，^10\n  好吗？" },
		{ "phone_toriel_9_1_1", "* (滴...)" },
		{ "phone_toriel_10_0_0", "tori_neutral`snd_txttor`* 您好。\n^10* 这里是TORIEL。" },
		{ "phone_toriel_10_0_1", "tori_happy`snd_txttor`* 啊，^10遗迹的第一个谜题。" },
		{ "phone_toriel_10_0_2", "tori_neutral`snd_txttor`* 我会告诉你遗迹的谜题是\n  如何运作的。" },
		{ "phone_toriel_10_0_3", "tori_worry`snd_txttor`* 但是你也知道，^10我跑得太快\n  都没来及说。" },
		{ "phone_toriel_10_0_4", "tori_neutral`snd_txttor`* 但是，^10你也可以就当那个\n  谜题没人动过。" },
		{ "phone_toriel_10_0_5", "tori_happy`snd_txttor`* 玩的开心，^10亲爱的！" },
		{ "phone_toriel_10_0_6", "* (滴...)" },
		{ "phone_toriel_10_1_0", "tori_neutral`snd_txttor`* 您好。\n^10* 这里是TORIEL。" },
		{ "phone_toriel_10_1_1", "tori_weird`snd_txttor`* 你需要我帮你假装解开\n  第一个谜题？" },
		{ "phone_toriel_10_1_2", "tori_weird`snd_txttor`* ..." },
		{ "phone_toriel_10_1_3", "tori_neutral`snd_txttor`* 从左下角的按钮开始。" },
		{ "phone_toriel_10_1_4", "tori_neutral`snd_txttor`* 逆时针转到左上角的按钮。" },
		{ "phone_toriel_10_1_5", "tori_neutral`snd_txttor`* 不要踩到中间的开关。" },
		{ "phone_toriel_10_1_6", "tori_neutral`snd_txttor`* 然后拉下墙上的开关。" },
		{ "phone_toriel_10_1_7", "tori_happy`snd_txttor`* 我希望我帮到你了！" },
		{ "phone_toriel_10_1_8", "* (滴...)" },
		{ "phone_toriel_10_0_0_h", "tori_neutral`snd_txttor`* 您好。\n^10* 这里是TORIEL。" },
		{ "phone_toriel_10_0_1_h", "tori_happy`snd_txttor`* 啊，^10遗迹的第一个谜题。" },
		{ "phone_toriel_10_0_2_h", "tori_worry`snd_txttor`* ...我不确定你问这干啥。" },
		{ "phone_toriel_10_0_3_h", "tori_worry`snd_txttor`* I told you everything\n  that you need to\n  know about puzzles." },
		{ "phone_toriel_10_0_4_h", "tori_neutral`snd_txttor`* If anything else\n  comes to mind, I\n  will tell you." },
		{ "phone_toriel_10_0_5_h", "* (滴...)" },
		{ "phone_toriel_10_1_0_h", "tori_neutral`snd_txttor`* 您好。\n^10* 这里是TORIEL。" },
		{ "phone_toriel_10_1_1_h", "tori_worry`snd_txttor`* Oh,^10 you are wondering\n  if anything came to\n  mind?" },
		{ "phone_toriel_10_1_2_h", "tori_neutral`snd_txttor`* ..." },
		{ "phone_toriel_10_1_3_h", "tori_worry`snd_txttor`* Unfortunately not." },
		{ "phone_toriel_10_1_5_h", "* (滴...)" },
		{ "phone_toriel_11_0_0", "tori_neutral`snd_txttor`* 您好。\n^10* 这里是TORIEL。" },
		{ "phone_toriel_11_0_1", "tori_worry`snd_txttor`* 墙上的开关？" },
		{ "phone_toriel_11_0_2", "tori_worry`snd_txttor`* 啊，^10那个谜题我都做完了，^10\n  所以我帮不了你。" },
		{ "phone_toriel_11_0_3", "tori_neutral`snd_txttor`* 抱歉。" },
		{ "phone_toriel_11_0_4", "* (滴...)" },
		{ "phone_toriel_11_1_0", "tori_weird`snd_txttor`* 不，^10千万别碰那个\n  拉不下来的拉杆。" },
		{ "phone_toriel_11_1_1", "* (滴...)" },
		{ "phone_toriel_11_1_0_h", "tori_weird`snd_txttor`* 不行，^10千万别碰最后的\n  开关。" },
		{ "phone_toriel_11_1_1_h", "* (滴...)" },
		{ "phone_toriel_12_0_0", "tori_neutral`snd_txttor`* 您好。\n^10* 这里是TORIEL。" },
		{ "phone_toriel_12_0_1", "tori_neutral`snd_txttor`* 哦，你找到那个人偶了？" },
		{ "phone_toriel_12_0_2", "tori_happy`snd_txttor`* 我很高兴他为你们带来了\n  一些帮助！" },
		{ "phone_toriel_12_0_3", "tori_worry`snd_txttor`* 我也希望你们没揍爆他。" },
		{ "phone_toriel_12_0_4", "tori_worry`snd_txttor`* 这人偶的设立是为了教导\n  其他可能不会战斗的人。" },
		{ "phone_toriel_12_0_5", "* (滴...)" },
		{ "phone_toriel_12_0_0_h", "tori_neutral`snd_txttor`* 您好。\n^10* 这里是TORIEL。" },
		{ "phone_toriel_12_0_1_h", "tori_neutral`snd_txttor`* Oh,^10 the training\n  dummy?" },
		{ "phone_toriel_12_0_2_h", "tori_happy`snd_txttor`* Yes,^05 well..." },
		{ "phone_toriel_12_0_3_h", "tori_blush`snd_txttor`* Oh,^05 that reminds\n  me!" },
		{ "phone_toriel_12_0_4_h", "tori_happy`snd_txttor`* Did you know that\n  a ghost lives in\n  the training dummy?" },
		{ "phone_toriel_12_0_5_h", "tori_neutral`snd_txttor`* One time,^05 when I\n  was honing my ACTing\n  skills..." },
		{ "phone_toriel_12_0_6_h", "tori_happy`snd_txttor`* It actually responded\n  to me!" },
		{ "phone_toriel_12_0_7_h", "tori_worry`snd_txttor`* What?^10\n* Was I hallucinating?" },
		{ "phone_toriel_12_0_8_h", "tori_wack`snd_txttor`* Hahaha!^10\n* That's silly!" },
		{ "phone_toriel_12_0_9_h", "* (滴...)" },
		{ "phone_toriel_12_1_0_h", "tori_wack`snd_txttor`* Let us drop this\n  topic." },
		{ "phone_toriel_12_1_1_h", "* (滴...)" },
		{ "phone_toriel_13_0_0", "tori_neutral`snd_txttor`* 您好。\n^10* 这里是TORIEL。" },
		{ "phone_toriel_13_0_1", "tori_worry`snd_txttor`*哦，^10尖刺地板？" },
		{ "phone_toriel_13_0_2", "tori_neutral`snd_txttor`* 额，^10大厅前的路显示了\n  一条安全的路径。" },
		{ "phone_toriel_13_0_3", "tori_neutral`snd_txttor`* 跟着走的话，^10就不会被扎到。" },
		{ "phone_toriel_13_0_4", "tori_happy`snd_txttor`* 希望我的帮助有用，^10亲爱的。" },
		{ "phone_toriel_13_0_5", "* (滴...)" },
		{ "phone_toriel_13_0_6", "su_annoyed`snd_txtsus`* 操，^05我还挺喜欢被扎的。" },
		{ "phone_toriel_13_1_0", "tori_neutral`snd_txttor`* 您好。\n^10* 这里是TORIEL。" },
		{ "phone_toriel_13_1_1", "tori_weird`snd_txttor`* ...^05Susie自己就想被扎？" },
		{ "phone_toriel_13_1_2", "tori_weird`snd_txttor`* ..." },
		{ "phone_toriel_13_1_3", "tori_wack`snd_txttor`* 额，希望她很享受这个谜题！" },
		{ "phone_toriel_13_1_4", "* (滴...)" },
		{ "phone_toriel_13_0_0_h", "tori_neutral`snd_txttor`* 您好。\n^10* 这里是TORIEL。" },
		{ "phone_toriel_13_0_1_h", "tori_worry`snd_txttor`*哦，^10尖刺地板？" },
		{ "phone_toriel_13_0_2_h", "tori_neutral`snd_txttor`* Well,^10 I already took\n  you through the\n  safe pathway." },
		{ "phone_toriel_13_0_3_h", "tori_neutral`snd_txttor`* 跟着走的话，^10就不会被扎到。" },
		{ "phone_toriel_13_0_4_h", "tori_happy`snd_txttor`* 希望我的帮助有用，^10亲爱的。" },
		{ "phone_toriel_13_0_5_h", "* (滴...)" },
		{ "phone_toriel_13_0_6_h", "su_annoyed`snd_txtsus`* 操，^05我还挺喜欢被扎的。" },
		{ "phone_toriel_13_1_0_h", "tori_neutral`snd_txttor`* 您好。\n^10* 这里是TORIEL。" },
		{ "phone_toriel_13_1_1_h", "tori_weird`snd_txttor`* ...^05Susie自己就想被扎？" },
		{ "phone_toriel_13_1_2_h", "tori_weird`snd_txttor`* ..." },
		{ "phone_toriel_13_1_3_h", "tori_wack`snd_txttor`* Did she not do\n  that earlier?" },
		{ "phone_toriel_13_1_4_h", "* (滴...)" },
		{ "phone_toriel_14_0_0", "tori_worry`snd_txttor`* 哦天哪..." },
		{ "phone_toriel_14_0_1", "tori_worry`snd_txttor`* 这里是\n  “独立的必经长廊”。" },
		{ "phone_toriel_14_0_2", "tori_neutral`snd_txttor`* 这是为了测试每一位\n  人类小孩的独立性\n  而建立的。" },
		{ "phone_toriel_14_0_3", "tori_neutral`snd_txttor`* 还好，^10你不用独立面对它。" },
		{ "phone_toriel_14_0_4", "tori_happy`snd_txttor`* 你有Susie陪你，^10对吧？" },
		{ "phone_toriel_14_0_5", "* (滴...)" },
		{ "phone_toriel_15_0_0", "tori_neutral`snd_txttor`* 您好。\n^10* 这里是TORIEL。" },
		{ "phone_toriel_15_0_1", "tori_worry`snd_txttor`* 哦，^10你说青蛙？" },
		{ "phone_toriel_15_0_2", "tori_happy`snd_txttor`* 那是Froggit！" },
		{ "phone_toriel_15_0_3", "tori_neutral`snd_txttor`* 他们头脑混乱，这点不可否认。\n^10  但他们并不邪恶。" },
		{ "phone_toriel_15_0_4", "tori_worry`snd_txttor`* 请不要攻击它们。" },
		{ "phone_toriel_15_0_5", "* (滴...)" },
		{ "phone_toriel_15_0_6", "su_inquisitive`snd_txtsus`* 好。" },
		{ "phone_toriel_15_1_0", "tori_neutral`snd_txttor`* 喂，^10Kris。" },
		{ "phone_toriel_15_1_1", "tori_worry`snd_txttor`* 我希望你不要攻击\n  Froggit。" },
		{ "phone_toriel_15_1_2", "* (滴...)" },
		{ "phone_toriel_15_1_0_h", "tori_neutral`snd_txttor`* 喂，^10我的孩子。" },
		{ "phone_toriel_15_1_1_h", "tori_worry`snd_txttor`* 我希望你不要攻击\n  Froggit。" },
		{ "phone_toriel_15_1_2_h", "* (滴...)" },
		{ "phone_toriel_16_0_0", "tori_neutral`snd_txttor`* 您好。\n^10* 这里是TORIEL。" },
		{ "phone_toriel_16_0_1", "tori_worry`snd_txttor`* 糖果房？" },
		{ "phone_toriel_16_0_2", "tori_happy`snd_txttor`* 那些糖是我给大伙留的。" },
		{ "phone_toriel_16_0_3", "tori_neutral`snd_txttor`* 要是需要的话，\n  你可以拿一个。" },
		{ "phone_toriel_16_0_4", "* (滴...)" },
		{ "phone_toriel_17_0_0", "tori_blush`snd_txttor`* 哦哦，^05Kris！^10\n* 我想起来了！" },
		{ "phone_toriel_17_0_1", "tori_neutral`snd_txttor`* 有些谜题会让你摔倒。" },
		{ "phone_toriel_17_0_2", "tori_worry`snd_txttor`* 务必告知Susie此事。" },
		{ "phone_toriel_17_0_3", "* (滴...)" },
		{ "phone_toriel_17_0_4", "su_side`snd_txtsus`* 你们俩刚刚说啥呢？" },
		{ "phone_toriel_17_0_0_h", "tori_blush`snd_txttor`* 哦哦，^05我的孩子！^10\n* 我想起来了！" },
		{ "phone_toriel_17_0_1_h", "tori_neutral`snd_txttor`* 有些谜题会让你摔倒。" },
		{ "phone_toriel_17_0_2_h", "tori_worry`snd_txttor`* 务必告知Susie此事。" },
		{ "phone_toriel_17_0_3_h", "* (滴...)" },
		{ "phone_toriel_17_0_4_h", "su_side`snd_txtsus`* 你们俩刚刚说啥呢？" },
		{ "phone_toriel_19_0_0", "tori_neutral`snd_txttor`* 您好。\n^10* 这里是TORIEL。" },
		{ "phone_toriel_19_0_1", "tori_worry`snd_txttor`* 碎砖迷宫？" },
		{ "phone_toriel_19_0_2", "tori_neutral`snd_txttor`* 跟着干净的小道走。" },
		{ "phone_toriel_19_0_3", "tori_happy`snd_txttor`* 过的开心，^05亲爱的。" },
		{ "phone_toriel_19_0_4", "tori_worry`snd_txttor`* 哦，^10对了，^10别踩树叶。" },
		{ "phone_toriel_19_0_5", "* (滴...)" },
		{ "phone_toriel_19_0_6", "su_smile`snd_txtsus`* 我们可太听了，^05是吧Kris？" },
		{ "phone_toriel_19_0_0_h", "tori_neutral`snd_txttor`* 您好。\n^10* 这里是TORIEL。" },
		{ "phone_toriel_19_0_1_h", "tori_worry`snd_txttor`* 碎砖迷宫？" },
		{ "phone_toriel_19_0_2_h", "tori_neutral`snd_txttor`* 跟着干净的小道走。" },
		{ "phone_toriel_19_0_3_h", "tori_happy`snd_txttor`* 过的开心，^05亲爱的。" },
		{ "phone_toriel_19_0_4_h", "tori_worry`snd_txttor`* 哦，^10对了，^10别踩树叶。" },
		{ "phone_toriel_19_0_5_h", "* (滴...)" },
		{ "phone_toriel_19_0_6_h", "su_smile`snd_txtsus`* 收到，^05那咱放心踩了。" },
		{ "phone_toriel_19_1_0", "tori_neutral`snd_txttor`* 您好。\n^10* 这里是TORIEL。" },
		{ "phone_toriel_19_1_1", "tori_worry`snd_txttor`* 你没踩树叶，^10对吧？" },
		{ "phone_toriel_19_1_2", "tori_weird`snd_txttor`* 你踩了？^10\n* 你还很骄傲？" },
		{ "phone_toriel_19_1_3", "tori_wack`snd_txttor`* 天了，^10你这孩子真有意思！" },
		{ "phone_toriel_19_1_4", "* (滴...)" },
		{ "phone_toriel_19_1_0_h", "tori_neutral`snd_txttor`* 您好。\n^10* 这里是TORIEL。" },
		{ "phone_toriel_19_1_1_h", "tori_worry`snd_txttor`* 你没踩树叶，^10对吧？" },
		{ "phone_toriel_19_1_2_h", "su_angry`snd_txtsus`* 进屋里就是踩！！！\n^05* 看谁踩谁，谁也拦不住！！！" },
		{ "phone_toriel_19_1_3_h", "tori_weird`snd_txttor`* ..." },
		{ "phone_toriel_19_1_4_h", "tori_wack`snd_txttor`* 我天，^10你真是个有趣的，^10\n  呃，Susie！" },
		{ "phone_toriel_19_1_5_h", "* (滴...)" },
		{ "phone_toriel_20_0_0", "tori_neutral`snd_txttor`* 您好。\n^10* 这里是TORIEL。" },
		{ "phone_toriel_20_0_1", "tori_worry`snd_txttor`* 石头？\n^05* 而且还会说话？" },
		{ "phone_toriel_20_0_2", "tori_neutral`snd_txttor`* 你知不知道四分之三的\n  石头..." },
		{ "phone_toriel_20_0_3", "tori_happy`snd_txttor`* 接受被你推吗？" },
		{ "phone_toriel_20_0_4", "tori_worry`snd_txttor`* 另一个，^10你可能得问问。" },
		{ "phone_toriel_20_0_5", "tori_wack`snd_txttor`* 或者如果他不让，^10\n  你可能就需要撇飞他了！" },
		{ "phone_toriel_20_0_6", "* (滴...)" },
		{ "phone_toriel_20_1_0", "tori_blush`snd_txttor`* 我扔没扔奇怪的石头？" },
		{ "phone_toriel_20_1_1", "tori_worry`snd_txttor`* 当然没有了。" },
		{ "phone_toriel_20_1_2", "tori_worry`snd_txttor`* 毕竟，^10我压力大的时候\n  才会那么干。" },
		{ "phone_toriel_20_1_3", "tori_wack`snd_txttor`* 当然，^10如果那块石头\n  因为我晚上浇花就骂我..." },
		{ "phone_toriel_20_1_4", "tori_wack`snd_txttor`* ..." },
		{ "phone_toriel_20_1_5", "tori_worry`snd_txttor`* 你懂我意思。" },
		{ "phone_toriel_20_1_6", "* (滴...)" },
		{ "phone_toriel_21_0_0", "tori_neutral`snd_txttor`* 您好。\n^10* 这里是TORIEL。" },
		{ "phone_toriel_21_0_1", "tori_weird`snd_txttor`* 桌子上的奶酪？" },
		{ "phone_toriel_21_0_2", "tori_worry`snd_txttor`* 千万别吃。\n* 你会得病的。" },
		{ "phone_toriel_21_0_3", "* (滴...)" },
		{ "phone_toriel_24_0_0", "tori_neutral`snd_txttor`* 您好。\n^10* 这里是TORIEL。" },
		{ "phone_toriel_24_0_1", "tori_worry`snd_txttor`* 抱歉，^05但我现在很忙。" },
		{ "phone_toriel_24_0_2", "tori_worry`snd_txttor`* 请仅在您确实需要我的\n  帮助时才致电。" },
		{ "phone_toriel_24_0_3", "* (滴...)" },
		{ "phone_toriel_26_0_0", "tori_neutral`snd_txttor`* 您好。\n^10* 这里是TORIEL。" },
		{ "phone_toriel_26_0_1", "tori_worry`snd_txttor`* 彩色开关？" },
		{ "phone_toriel_26_0_2", "tori_neutral`snd_txttor`* 每个房间的开关排列\n  都相同。" },
		{ "phone_toriel_26_0_3", "tori_neutral`snd_txttor`* 因此它们在每个房间中的\n  位置都相同。" },
		{ "phone_toriel_26_0_4", "tori_worry`snd_txttor`* 如果我没记错的话，^05\n  蓝色开关在房间入口附近..." },
		{ "phone_toriel_26_0_5", "tori_worry`snd_txttor`* 蓝色开关离出口不远..." },
		{ "phone_toriel_26_0_6", "tori_worry`snd_txttor`* 而绿色按钮在转角处。" },
		{ "phone_toriel_26_0_7", "tori_happy`snd_txttor`* 我希望能帮上忙，^05\n  亲爱的。" },
		{ "phone_toriel_26_0_8", "* (滴...)" },
		{ "phone_toriel_27_0_0", "tori_neutral`snd_txttor`* 您好。\n^10* 这里是TORIEL。" },
		{ "phone_toriel_27_0_1", "tori_worry`snd_txttor`* 彩色开关？" },
		{ "phone_toriel_27_0_2", "tori_neutral`snd_txttor`* 每个房间的开关排列\n  都相同。" },
		{ "phone_toriel_27_0_3", "tori_neutral`snd_txttor`* 因此它们在每个房间中的\n  位置都相同。" },
		{ "phone_toriel_27_0_4", "tori_worry`snd_txttor`* 如果我没记错的话，^05\n  蓝色开关在房间入口附近..." },
		{ "phone_toriel_27_0_5", "tori_worry`snd_txttor`* 蓝色开关离出口不远..." },
		{ "phone_toriel_27_0_6", "tori_worry`snd_txttor`* 而绿色按钮在转角处。" },
		{ "phone_toriel_27_0_7", "tori_happy`snd_txttor`* 我希望能帮上忙，^05\n  亲爱的。" },
		{ "phone_toriel_27_0_8", "* (滴...)" },
		{ "phone_toriel_28_0_0", "tori_neutral`snd_txttor`* 您好。\n^10* 这里是TORIEL。" },
		{ "phone_toriel_28_0_1", "tori_worry`snd_txttor`* 彩色开关？" },
		{ "phone_toriel_28_0_2", "tori_neutral`snd_txttor`* 每个房间的开关排列\n  都相同。" },
		{ "phone_toriel_28_0_3", "tori_neutral`snd_txttor`* 因此它们在每个房间中的\n  位置都相同。" },
		{ "phone_toriel_28_0_4", "tori_worry`snd_txttor`* 如果我没记错的话，^05\n  蓝色开关在房间入口附近..." },
		{ "phone_toriel_28_0_5", "tori_worry`snd_txttor`* 蓝色开关离出口不远..." },
		{ "phone_toriel_28_0_6", "tori_worry`snd_txttor`* 而绿色按钮在转角处。" },
		{ "phone_toriel_28_0_7", "tori_happy`snd_txttor`* 我希望能帮上忙，^05\n  亲爱的。" },
		{ "phone_toriel_28_0_8", "* (滴...)" },
		{ "phone_toriel_29_0_0", "tori_neutral`snd_txttor`* 您好。\n^10* 这里是TORIEL。" },
		{ "phone_toriel_29_0_1", "tori_worry`snd_txttor`* 彩色开关？" },
		{ "phone_toriel_29_0_2", "tori_neutral`snd_txttor`* 每个房间的开关排列\n  都相同。" },
		{ "phone_toriel_29_0_3", "tori_neutral`snd_txttor`* 因此它们在每个房间中的\n  位置都相同。" },
		{ "phone_toriel_29_0_4", "tori_worry`snd_txttor`* 如果我没记错的话，^05\n  蓝色开关在房间入口附近..." },
		{ "phone_toriel_29_0_5", "tori_worry`snd_txttor`* 蓝色开关离出口不远..." },
		{ "phone_toriel_29_0_6", "tori_worry`snd_txttor`* 而绿色按钮在转角处。" },
		{ "phone_toriel_29_0_7", "tori_happy`snd_txttor`* 我希望能帮上忙，^05\n  亲爱的。" },
		{ "phone_toriel_29_0_8", "* (滴...)" },
		{ "phone_home_0_0", "* ..." },
		{ "phone_home_0_1", "* 好像没在运作。" },
		{ "phone_home_1_0", "torid_happy`snd_txttor`* My,^05 Kris,^05 I am rather\n  impressed." },
		{ "phone_home_1_1", "torid_wack`snd_txttor`* You and Susie woke up\n  before I did!" },
		{ "phone_home_1_2", "torid_relief`snd_txttor`* You must have really\n  wanted to spend\n  time together." },
		{ "phone_home_1_3", "torid_neutral`snd_txttor`* I hope that you two\n  have fun wherever you\n  are." },
		{ "phone_home_1_4", "* (滴...)" },
		{ "phone_home_2_0", "torid_happy`snd_txttor`* 喂，^10Kris。" },
		{ "phone_home_2_1", "torid_neutral`snd_txttor`* 我终于有时间重新刷那面\n  受损的墙壁了。" },
		{ "phone_home_2_2", "torid_worry`snd_txttor`* 这样我想起了..." },
		{ "phone_home_2_3", "* 你知道闪电的效果。\n  ^05对吧？" },
		{ "phone_home_2_4", "torid_worry`snd_txttor`* 如果它直接劈中某个人，\n  那个人就会直接没命。" },
		{ "phone_home_2_5", "torid_worry`snd_txttor`* 今天天气不错，\n  我也不知道为什么会想起\n  这个。" },
		{ "phone_home_2_6", "torid_wack`snd_txttor`* 所以只要你没见到\n  一位能召唤闪电的\n  魔法师画家..." },
		{ "phone_home_2_7", "torid_neutral`snd_txttor`* 你就不会有事的。" },
		{ "phone_home_2_8", "torid_neutral`snd_txttor`* 注意安全，^05亲爱的。" },
		{ "phone_home_2_9", "* (滴...)" },
		{ "phone_home_3_0", "torid_happy`snd_txttor`* 喂，^10Kris。" },
		{ "phone_home_3_1", "torid_neutral`snd_txttor`* 我终于有时间重新刷那面\n  受损的墙壁了。" },
		{ "phone_home_3_2", "torid_worry`snd_txttor`* 这样我想起了..." },
		{ "phone_home_3_3", "* 你知道闪电的效果。\n  ^05对吧？" },
		{ "phone_home_3_4", "torid_worry`snd_txttor`* ...^05 Kris?^10\n* 你还好吗，^05亲爱的？" },
		{ "phone_home_3_5", "torid_worry`snd_txttor`* 你听着不是很好。" },
		{ "phone_home_3_6", "torid_neutral`snd_txttor`* 要是你想回家的话^05\n  我随时欢迎。" },
		{ "phone_home_3_7", "torid_worry`snd_txttor`* 我不想让你带着病出去。" },
		{ "phone_home_3_8", "* (滴...)" },
		{ "phone_home_4_0", "torid_happy`snd_txttor`* 喂，^10Kris。" },
		{ "phone_home_4_1", "torid_neutral`snd_txttor`* 我正在看一本关于\n  鼹鼠的书。" },
		{ "phone_home_4_2", "torid_happy`snd_txttor`* 你知道它们非常擅长\n  找朋友吗？" },
		{ "phone_home_4_3", "torid_neutral`snd_txttor`* 如果你很友善的话它们会\n  愿意沟通的..." },
		{ "phone_home_4_4", "torid_neutral`snd_txttor`* ...抑或你是一个肉食动物。" },
		{ "phone_home_4_5", "torid_happy`snd_txttor`* 他们也很可爱！" },
		{ "phone_home_4_6", "torid_worry`snd_txttor`* 所以你要是碰到了\n  的话，友善点。" },
		{ "phone_home_4_7", "torid_neutral`snd_txttor`* 他不会恶意伤害你的。" },
		{ "phone_home_4_8", "* (滴...)" },
		{ "phone_home_5_0", "torid_happy`snd_txttor`* 喂，^10Kris。" },
		{ "phone_home_5_1", "torid_weird`snd_txttor`* 额...^15你那边风怎么那么大。" },
		{ "phone_home_5_2", "torid_blush`snd_txttor`* 我这边今天可是\n  一点风都没有的啊。" },
		{ "phone_home_5_3", "torid_mad`snd_txttor`* 你到底在哪？" },
		{ "phone_home_5_4", "torid_weird`snd_txttor`* ...^10在地底的一个雪封\n  森林？\n^10* 还有什么维度穿越？！" },
		{ "phone_home_5_5", "torid_mad`snd_txttor`* Kris..." },
		{ "phone_home_5_6", "torid_worry`snd_txttor`* ...^10照看好自己。" },
		{ "phone_home_5_7", "* (滴...)" },
		{ "phone_home_e_0", "torid_happy`snd_txttor`* 喂，^10Kris。" },
		{ "phone_home_e_1", "torid_weird`snd_txttor`* 唔...^15我好像在你那\n  背景音听到了些什么。" },
		{ "phone_home_e_2", "torid_mad`snd_txttor`* 你到底在哪？" },
		{ "phone_home_e_3", "torid_weird`snd_txttor`* ...^10 * 维度穿越？！^10\n* 带着Susie还有Noelle？！" },
		{ "phone_home_e_4", "torid_mad`snd_txttor`* Kris..." },
		{ "phone_home_e_5", "torid_worry`snd_txttor`* ...^10照看好自己。" },
		{ "phone_home_e_6", "* (滴...)" },
		{ "phone_home_6_0", "torid_happy`snd_txttor`* 喂，^10Kris。" },
		{ "phone_home_6_1", "torid_neutral`snd_txttor`* ..." },
		{ "phone_home_6_2", "torid_worry`snd_txttor`* ...\n* ..." },
		{ "phone_home_6_3", "torid_weird`snd_txttor`* ...\n* ...\n* ..." },
		{ "phone_home_6_4", "torid_confused`snd_txttor`* ...?" },
		{ "phone_home_6_5", "torid_worry`snd_txttor`* Kris...?^05\n* Hello?" },
		{ "phone_home_6_6", "* (滴...)" },
		{ "phone_home_7_0", "torid_worry`snd_txttor`* Kris..." },
		{ "phone_home_7_1", "torid_weird`snd_txttor`* I have no clue\n  where you even are..." },
		{ "phone_home_7_2", "torid_worry`snd_txttor`* But if you need\n  assistance,^05 I will see\n  what I can do." },
		{ "phone_home_7_3", "torid_wack`snd_txttor`* Perhaps the angel will\n  grant me motherly\n  insight!" },
		{ "phone_home_7_4", "torid_worry`snd_txttor`* Do be careful,^05 okay?" },
		{ "phone_home_7_5", "* (滴...)" },
		{ "phone_home_8_0", "torid_neutral`snd_txttor`* 喂，^10Kris。" },
		{ "phone_home_8_1", "torid_worry`snd_txttor`* What?^05\n* Letter from a killer\n  skeleton?" },
		{ "phone_home_8_2", "torid_worry`snd_txttor`* Hmm..." },
		{ "phone_home_8_3", "torid_neutral`snd_txttor`* Does the skeleton know\n  magic?" },
		{ "phone_home_8_4", "torid_worry`snd_txttor`* If he does,^05 then\n  I would not recommend\n  opening the letter." },
		{ "phone_home_8_5", "torid_weird`snd_txttor`* Who knows what they\n  could have placed in\n  it?" },
		{ "phone_home_8_6", "torid_neutral`snd_txttor`* So,^05 just walk past\n  it." },
		{ "phone_home_8_7", "torid_happy`snd_txttor`* I hope that helps,^05\n  dear." },
		{ "phone_home_8_8", "* (滴...)" },
		{ "phone_home_9_0", "torid_neutral`snd_txttor`* 喂，^10Kris。" },
		{ "phone_home_9_1", "torid_worry`snd_txttor`* If I may ask..." },
		{ "phone_home_9_2", "torid_worry`snd_txttor`* What did you mean\n  by \"killer skeleton?\"" },
		{ "phone_home_9_3", "torid_neutral`snd_txttor`* Surely it isn't\n  someone we know,^05 right?" },
		{ "phone_home_9_4", "torid_neutral`snd_txttor`* ..." },
		{ "phone_home_9_5", "torid_blush`snd_txttor`* ...^05 It was Sans???" },
		{ "phone_home_9_6", "torid_weird`snd_txttor`* No,^05 no,^05 that cannot\n  be right." },
		{ "phone_home_9_7", "torid_worry`snd_txttor`* He would never hurt\n  anyone!" },
		{ "phone_home_9_8", "torid_worry`snd_txttor`* Surely he must have\n  suffered some sort of\n  tragedy to act that way." },
		{ "phone_home_9_9", "torid_worry`snd_txttor`* Otherwise,^05 I would say\n  it isn't him." },
		{ "phone_home_9_10", "* (滴...)" },
		{ "phone_home_10_0", "torid_neutral`snd_txttor`* 喂，^10Kris。" },
		{ "phone_home_10_1", "torid_weird`snd_txttor`* ... You were attacked\n  by Sans???" },
		{ "phone_home_10_2", "torid_worry`snd_txttor`* I am still in\n  disbelief that he\n  would do that." },
		{ "phone_home_10_3", "torid_neutral`snd_txttor`* I've been trying\n  to find him around\n  town." },
		{ "phone_home_10_4", "torid_neutral`snd_txttor`* But it seems he's\n  at home,^05 not answering\n  the door." },
		{ "phone_home_10_5", "torid_worry`snd_txttor`* How odd..." },
		{ "phone_home_10_6", "torid_worry`snd_txttor`* Just stay safe,^05\n  honey." },
		{ "phone_home_10_7", "* (滴...)" },
		{ "phone_home_11_0", "torid_neutral`snd_txttor`* 喂，^10Kris。" },
		{ "phone_home_11_1", "torid_wack`snd_txttor`* Oh,^05 you are finally\n  some place safe?" },
		{ "phone_home_11_2", "torid_relief`snd_txttor`* Thank goodness..." },
		{ "phone_home_11_3", "torid_worry`snd_txttor`* I was so worried\n  that you would\n  get hurt,^05 or worse." },
		{ "phone_home_11_4", "torid_worry`snd_txttor`* I still am worried." },
		{ "phone_home_11_5", "torid_worry`snd_txttor`* However on Earth\n  you ended up in\n  another world..." },
		{ "phone_home_11_6", "torid_worry`snd_txttor`* I hope you can\n  find your way home." },
		{ "phone_home_11_7", "torid_worry`snd_txttor`* Stay safe,^05 dear." },
		{ "phone_home_11_8", "* (滴...)" },
		{ "uno_default", "Uno!" },
		{ "uno_papyrus_0", "UNO!" },
		{ "uno_papyrus_1", "UNO!\n^10GET BONED, \nBONEHEAD!" },
		{ "uno_papyrus_2", "UNO!\n^10I CAN SMELL \nVICTORY!" },
		{ "uno_susie_0", "Uno." },
		{ "uno_susie_2", "Uno!^10\nSo close..." },
		{ "uno_susie_1", "Uno.^10\nGet drawing, punk." },
		{ "uno_noelle_0", "Uno!" },
		{ "uno_noelle_1", "Uno!\n^10Oops,^10 sorry!" },
		{ "uno_noelle_2", "Uno!\n^10I've got this!" },
		{ "uno_papyrus_hard_0", "UNO!" },
		{ "uno_papyrus_hard_1", "UNO!" },
		{ "uno_papyrus_hard_2", "UNO!" },
		{ "uno_check_kris", "* Error lol" },
		{ "uno_check_susie", "* SUSIE - 攻击{0} 防御{1}\n* 头脑简单的“刻薄女孩”\n  对UNO很是苦手。" },
		{ "uno_check_noelle", "* NOELLE - 攻击{0} 防御{1}\n* 喜庆的，乐观还有点胆小的\n  邻家女孩。" },
		{ "uno_check_papyrus", "* PAPYRUS - 攻击20 防御20\n* 口头禅是：“捏嘿嘿！”" },
		{ "uno_check_papyrus_hard", "* PAPYRUS - 攻击20 防御20\n* 口头禅是：“捏嘿嘿！”" },
		{ "music/mus_date", "Dating Start!`From UNDERTALE\nBy Toby Fox" },
		{ "music/mus_date_fight", "Dating Fight!`From UNDERTALE\nBy Toby Fox" },
		{ "music/mus_battle1", "Enemy Approaching`From UNDERTALE\nBy Toby Fox" },
		{ "music/mus_battle2", "Stronger Monsters`From UNDERTALE\nBy Toby Fox" },
		{ "music/mus_muscle", "sans.`From UNDERTALE\nBy Toby Fox" },
		{ "music/mus_sansfight", "Song That Might Play When You Fight Sans`From UNDERTALE\nBy Toby Fox" },
		{ "music/mus_undyneboss", "Spear of Justice`From UNDERTALE\nBy Toby Fox" },
		{ "music/mus_justice", "Beta Undyne Battle`From UNDERTALE\nBy Toby Fox" },
		{ "music/mus_spider", "Spider Dance`From UNDERTALE\nBy Toby Fox" },
		{ "music/mus_mewmew", "Mad Mew Mew`From UNDERTALE\nBy Toby Fox" },
		{ "music/mus_battledelta", "Rude Buster`From DELTARUNE\nBy Toby Fox" },
		{ "music/mus_checkers", "Checker Dance`From DELTARUNE\nBy Toby Fox" },
		{ "music/mus_mansion", "Pandora Palace`From DELTARUNE\nBy Toby Fox" },
		{ "music/mus_queen_boss", "Attack of the Killer Queen`From DELTARUNE\nBy Toby Fox" },
		{ "music/mus_spamton_battle", "NOW'S YOUR CHANCE TO BE A`From DELTARUNE\nBy Toby Fox" },
		{ "music/mus_spamton_neo_mix_ex_wip", "BIG SHOT`From DELTARUNE\nBy Toby Fox" },
		{ "music/mus_mansion_entrance", "Elegant Entrance`From DELTARUNE\nBy Toby Fox" },
		{ "music/mus_berdly_chase", "Smart Race`From DELTARUNE\nBy Toby Fox" },
		{ "music/mus_battle", "Rude Encounter`From DELTATRAVELER\nBy RENREN" },
		{ "music/mus_battle_hard", "Ruder Monsters`From DELTATRAVELER\nBy RENREN" },
		{ "music/mus_battle_eb", "Battle Against A Rude Opponent`From DELTATRAVELER\nBy LazyGales" },
		{ "music/mus_unsettling_battle", "Battle Against An Unsettling Opponent`From Earthbound\nBy Keiichi Suzuki & Hirokazu Tanaka" },
		{ "music/mus_floweyboss", "FLOWEY`From DELTATRAVELER\nBy RENREN" },
		{ "music/mus_pokeyboss_intro", "Porky's Mayhem`From DELTATRAVELER\nBy LazyGales" },
		{ "music/mus_vsufsans_intro", "Eye for an Eye`From GG!UNDERFELL\nBy TheTuneHero" },
		{ "music/mus_frankness_intro", "Frankness`From UNDERTALE: Papyrus's Belief\nBy Nikolas" },
		{ "music/mus_sandstorm_approaching", "Sandstorm Approaching`From UNDERTALE Yellow\nBy MyNewSoundtrack" },
		{ "music/mus_deal_em_out", "Deal 'Em Out`From UNDERTALE Yellow\nBy emBer" },
		{ "music/mus_decibat", "Fever Pitch`From UNDERTALE Yellow\nBy MasterSwordRemix & MyNewSoundtrack" },
		{ "music/mus_dalv_intro", "Forlorn`From UNDERTALE Yellow\nBy MasterSwordRemix & MyNewSoundtrack" },
		{ "music/mus_protocol", "Protocol`From UNDERTALE Yellow\nBy MasterSwordRemix & MyNewSoundtrack" },
		{ "music/mus_apprehension", "Apprehension`From UNDERTALE Yellow\nBy MasterSwordRemix & MyNewSoundtrack" },
		{ "music/mus_showdown", "Showdown!`From UNDERTALE Yellow\nBy MasterSwordRemix" },
		{ "music/mus_guns_blazing", "Guns Blazing`From UNDERTALE Yellow\nBy MasterSwordRemix & MyNewSoundtrack" },
		{ "music/mus_end_of_the_line", "END OF THE LINE_`From UNDERTALE Yellow\nBy Figburn" },
		{ "music/mus_some_point_of_no_return", "Some Point of No Return`From UNDERTALE Yellow\nBy MasterSwordRemix & MyNewSoundtrack" }
	};

	public static string GetText(string key, params string[] formatting)
	{
		if (english.ContainsKey(key))
		{
			return string.Format(english[key], formatting);
		}
		Debug.LogWarning("invalid localizer key " + key);
		return "INVALID";
	}

	public static bool HasText(string key)
	{
		return english.ContainsKey(key);
	}

	public static Dictionary<string, string>.KeyCollection GetKeys()
	{
		return english.Keys;
	}

	public static string GetGlobalFont()
	{
		return "DTM-Sans";
	}

	public static string[] FormatArray(string[] strings, params object[] vars)
	{
		List<string> list = new List<string>();
		foreach (string format in strings)
		{
			list.Add(string.Format(format, vars));
		}
		return list.ToArray();
	}
}

